export {default as Banner1} from './banners/1.jpg'
export {default as Banner2} from './banners/2.jpg'
export {default as AboutUniCoffeeRoastery} from './images/AboutUniCoffeeRoastery.jpg'
export {default as GreenCoffeeDeepProcessing} from './images/GreenCoffeeDeepProcessing.jpg'
export {default as GreenCoffeeEcologicalFarming} from './images/GreenCoffeeEcologicalFarming.jpg'
export {default as GreenCoffeeIsolateModel} from './images/GreenCoffeeIsolateModel.jpg'
export {default as GreenCoffeeRelatedPartyValue} from './images/GreenCoffeeRelatedPartyValue.jpg'
export {default as GreenCoffeeVissionAndMission} from './images/GreenCoffeeVissionAndMission.jpg'
export {default as GreenCoffeeWoodBlock} from './images/GreenCoffeeWoodBlock.jpg'
export {default as GreenCoffeeLarge} from './images/GreenCoffeeLarge.jpg'
export {default as ContactAndSupport} from './images/ContactAndSupport.png'
export {default as RoastedCoffeeLanding} from './images/RoastedCoffeeLanding.jpg'
export {default as RoastedCoffeeProcessingAndPackaging} from './images/RoastedCoffeeProcessingAndPackaging.jpg'
export {default as RoastedCoffeeSupplied} from './images/RoastedCoffeeSupplied.jpg'

export {default as GoogleIcon} from './svg/google-icon.svg'
